services:
  - type: web
    name: computer-inventory-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: BASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
